feat(CEMA-4): Create Supplier API (index, update,delete)
dimif24/cema pull request #3
Opened 2024-06-08 17:39 UTC by SABBIDO7

2024-06-13 20:41 UTC, SABBIDO7 reviewed
- On deleting the supplier the SupplierId in the product will be removed and the product will be without supplier And the contactPersons linked to the supplier will be deleted.

- On deleting contactPerson the contact person will be deleted also form the supplier contactList.

- If we want to change or erase a supplier from a specific product this functionality will be made from the UpdateProduct Endpoint from the product site not from supplier site.

2024-06-13 23:01 UTC, dimif24 requested changes

2024-06-14 04:46 UTC, SABBIDO7 commented on API/Dto/SupplierDTO.cs
> +        [EmailAddress]
> hal field chu bta3mil?

eza aamthke aan [EmailAddress] betshayik eza l format taba3 l email wosil as an email format Hyde tarakta in let law eemlneha men l front mnerjaa men shay bl back mama nekhsar she

2024-06-14 04:49 UTC, SABBIDO7 commented on API/Dto/SupplierDTO.cs
> +    public class SupplierDto
> Esem el class sah, bass chuf esm l file SupplierDTO.cs lezim SupplierDto.cs nel7a2 convention

Done fixed

2024-06-14 04:52 UTC, SABBIDO7 commented on API/Dto/SupplierDTO.cs
> +        [Required]
> ne7na bi DTO mich be entity hole elun lzum ??

We are ensuring that the data li waste from the front end contains ejbare Jayda l field haste and hek w betsahil aktr to find the bugs

2024-06-14 04:53 UTC, SABBIDO7 commented on API/Controllers/SuppliersController.cs
> +        [HttpGet("All")]
> route Get /Suppliers

Done kennel bede ehkik lashouf ezza mnaamela all kamn bl productsbas maak ha2 hek aandam

2024-06-14 04:55 UTC, SABBIDO7 commented on API/Controllers/SuppliersController.cs
> +        [HttpPost("Add")]
> RESTful Best Practice According to RESTful best practices, it's recommended to use the HTTP method to describe the action rather than including the action in the URL. This means you might not need /add or /create at all. Instead, you can rely on the HTTP POST method to indicate that you are adding or creating a new resource.
> 
> **Recommended Approach** Resource-Oriented URL: Use the base URL for the collection and rely on the HTTP method to indicate the action. URL: POST /api/suppliers This approach is more in line with REST principles and is commonly used in RESTful API design.
> 
> ya3ne inta men wara l post bta3rif ano create / eza put update / eza get ya3ne index

got it!

2024-06-14 05:00 UTC, SABBIDO7 commented on API/Controllers/SuppliersController.cs
> +        [HttpPost("Add")]
> > RESTful Best Practice According to RESTful best practices, it's recommended to use the HTTP method to describe the action rather than including the action in the URL. This means you might not need /add or /create at all. Instead, you can rely on the HTTP POST method to indicate that you are adding or creating a new resource.
> > **Recommended Approach** Resource-Oriented URL: Use the base URL for the collection and rely on the HTTP method to indicate the action. URL: POST /api/suppliers This approach is more in line with REST principles and is commonly used in RESTful API design.
> > ya3ne inta men wara l post bta3rif ano create / eza put update / eza get ya3ne index
> 
> got it! bas eemlin man l contactPerson bi nfs l controller bedna nsir nekhlak controller lahalo kerme l contactPerson

2024-06-16 21:57 UTC, dimif24 approved these changes

2024-06-16 21:58 UTC, merged